TiDev Banner Copy Updates
tidev/titanium-cli pull request #558
Opened 2022-03-23 23:50 UTC by joshualambert

This PR updates the Titanium banner that displays to:

1. Display TiDev as the project copyright maintainer.
2. Promote the Titanium Slack community.
3. Promote the TiDev Liberapay link.

It displays like this on iTerm+ZSH like this:

<img width="942" alt="Screen Shot 2022-03-23 at 6 50 31 PM" src="https://user-images.githubusercontent.com/1421842/159814960-1d99dc1a-c653-4397-a1bd-d475137d348f.png">

2022-03-24 04:57 UTC, caspahouzer commented
I’m missing more donation possibilities. Please let us setup GitHub sponsors asap

2022-03-24 12:09 UTC, m1ga commented on lib/logger.js
> +		logger.log(__('- Remember! Titanium is a community supported open-source project and relies on donations for on-going development.'));
I would remove the `Remember!` from the line

2022-03-24 12:37 UTC, cb1kenobi requested changes

2022-03-24 12:37 UTC, cb1kenobi commented on package.json
> +	"description": "TiDev Titanium Command line",
No need to say TiDev here.

2022-03-24 12:37 UTC, cb1kenobi commented on package.json
> +		"copyright": "Copyright (c) 2012-2022, TiDev, Inc. All Rights Reserved.",
I have been waiting to discuss the copyright before changing it. I'm not a lawyer, so I don't know if we can change it, or if we can, maybe we just reset the year to 2022?

2022-03-24 12:37 UTC, cb1kenobi commented on lib/logger.js
> +		logger.log(__('- Support the project here: %s', 'https://liberapay.com/tidev'.cyan));
I profoundly disagree with putting any mention of donations in the CLI output. I've already said time and time again, Titanium cannot sustain off donations. Titanium is open source. It is free. The only way Titanium will survive is if we get people to contribute. You set a precedence when you ask for donations to fund development. It's unfair to all the contributors that work on Titanium for free. Soon, nobody will want to contribute for free.

2022-03-24 12:37 UTC, cb1kenobi commented on lib/logger.js
> +		logger.log(__('- Join the TiDev Slack community here: %s \n', 'https://tislack.org'.cyan));
Why are we putting the Slack URL in the CLI output? This banner output is already too big, too many lines. I would suggest just displaying a link to https://titaniumsdk.com. That's where the docs are. That's where we want to funnel people to go first for help.

2022-03-24 12:37 UTC, cb1kenobi commented on package.json
>  		"appcelerator",
I've been removing "appcelerator" from the keywords.

2022-04-25 11:34 UTC, caspahouzer approved these changes
We have to MAKE MONEY. This is one way to generate attention

2022-04-25 11:35 UTC, caspahouzer commented
We should change the donation link to a page on tidev.io or titaniumsdk.com as soon as we have multiple donation possibilities

2022-04-25 11:43 UTC, m1ga commented
> We have to MAKE MONEY. This is one way to generate attention

I would just keep it at one line with a link to titaniumsdk.com (or github). In my opinion this is not the place to ask for donations. 
If you build an app it will scroll through anyways and you don't see it. If I want to see the help for a command I don't want to be bothered with that lines all the time.

Add it as a post-install message, so every new installation will be presented with a message, but not in every command.

2022-04-25 15:56 UTC, cb1kenobi commented
I agree with @m1ga. As stated before, I would not like to see a donation link in the CLI. However, if we add a donation link to the CLI, we should point it to a distinct CLI-specific URL that we can tie into analytics to see if anyone actually goes to the link.

Also, you can no longer have post install scripts print messages after installing an npm package. npm 7 and newer silence stdout and there's no way I have come up with around it. We'd have to do a first run thing.

2022-05-13 11:32 UTC, caspahouzer commented
Are there any news for this? @joshualambert

2024-05-10 19:19 UTC, closed without merging